{"name": "test_eval[6*9-42]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 54 == 42\n +  where 54 = eval('6*9')", "trace": "test_input = '6*9', expected = 42\n\n    @pytest.mark.parametrize(\"test_input,expected\", [(\"3+5\", 8), (\"2+4\", 6), (\"6*9\", 42)])\n    def test_eval(test_input, expected):\n>       assert eval(test_input) == expected\nE       AssertionError: assert 54 == 42\nE        +  where 54 = eval('6*9')\n\nAllureTestReports.py:42: AssertionError"}, "parameters": [{"name": "test_input", "value": "'6*9'"}, {"name": "expected", "value": "42"}], "start": 1580204610741, "stop": 1580204610741, "uuid": "c0051bf9-9a3d-402d-8a2d-621a3ce74181", "historyId": "49c57ab433bd9527a3332f390c7824a5", "testCaseId": "e8daa926f8bee5dd47edfdc7bf88abe2", "fullName": "AllureTestReports#test_eval", "labels": [{"name": "suite", "value": "AllureTestReports"}, {"name": "host", "value": "USBLRNPAVANKUM1"}, {"name": "thread", "value": "16720-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "AllureTestReports"}]}